### ISSUE TITLE
Add a way to register the vote data root hash

### ISSUE THREAD

**Issue by Geod24** [bpfkorea/boa-sdk-ts#17]
```
2. Registering vote data root hash
Save the hashed voting data after the vote ends on the BOA blockchain
- input:
- root_hash: the merkle root hash of vote data
- private_key?: private key of Votera server 
```

Blocked on the ability to do that in Agora.

**Comment by MichaelKim20** [comment]
In my opinion, the following input values will be needed.
- input
> - proposal id
> - vote id
> - root_hash : The merkle root hash of vote data
> - public_key : This should already be registered in Stoa. So this may be omitted.
> - signature : Sign information to be verified by the public key of the registered Votera server, information signed by the private key

 of the Votera server.

**Comment by Geod24** [comment]
Following our whiteboarding session, here are the input parameters of the function:
```
- Input[] utxos => An array of 1 or more UTXOs to be spent
- Key[] keys => An array of length matching `utxos` (the first parameter) which are the keys controlling the UTXOs
- ubyte[] data =>  The data to store
- Address refund => The address to which to send the refund
```

The function needs to compute the price of the data, then send whatever's left from the input to the `refund` address.
The function needs to error out if the input is not enough, or any of the parameters is invalid.

D-like example:
```D
Transaction createDataTransaction (in Input[]  utxos, in Key[] keys, in ubyte[] data, in Address refund);
```
