### ISSUE TITLE
There is a problem with using BigInt in React-Native

### ISSUE THREAD

**Issue by MichaelKim20** [bpfkorea/boa-sdk-ts#72]
![image](https://user-images.githubusercontent.com/11639939/102727141-4dbf3080-4367-11eb-9bad-d01c73bbca19.png)

**Comment by Geod24** [comment]
[BigInt support started with Safari 14](https://caniuse.com/bigint), released September 2020.

**Comment by MichaelKim20** [comment]
> [BigInt support started with Safari 14](https://caniuse.com/bigint), released September 2020.

Can I just use BigInt? If there is another alternative, we can use the JSBI.

**Comment by MichaelKim20** [comment]
This is an issue raised by the RNS wallet development team.
https://github.com/facebook/react-native/issues/28492
we got trouble of BigInt challenge again in React Native
Can we change BigInt from BOA SDK or any other solutions
In most cases, React Native will use JavaScriptCore, the JavaScript engine that powers Safari. Note that on iOS, JavaScriptCore does not use JIT due to the absence of writable executable memory in iOS apps.

**Comment by MichaelKim20** [comment]
I changed the title "There is a problem with using BigInt in React-Native"
